/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import UI_produtos.UI_caixa_de_som1;
import UI_produtos.UI_cooler1;
import UI_produtos.UI_monitor1;
import UI_produtos.UI_gabinete2;
import UI_produtos.UI_headset1;
import UI_produtos.UI_headset2;
import UI_produtos.UI_monitor1;
import UI_produtos.UI_monitor2;
import UI_produtos.UI_mouse1;
import UI_produtos.UI_mouse2;
import UI_produtos.UI_mousepad1;
import UI_produtos.UI_mousepad22;
import UI_produtos.UI_mousepad22;
import UI_produtos.UI_placa_de_video1;
import UI_produtos.UI_roteador1;
import UI_produtos.UI_tecladoo1;
import UI_produtos.UI_tecladoo22;
import UI_produtos.UI_webcam1;
import UI_produtos.UI_webcam22;

/**
 *
 * @author Administrator
 */
public class UI_produtos extends javax.swing.JFrame {

    /**
     * Creates new form UI_teste_de_loja
     */
    public UI_produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        primeiro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_historico = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_login1 = new javax.swing.JButton();
        painel_monitor1 = new javax.swing.JPanel();
        btn_monitor1 = new javax.swing.JButton();
        txt_descricao_monitor1 = new javax.swing.JLabel();
        txt_preco_monitor1 = new javax.swing.JLabel();
        pianel_telcado_1 = new javax.swing.JPanel();
        btn_teclado1 = new javax.swing.JButton();
        txt_descricao_teclado1 = new javax.swing.JLabel();
        txt_preco_teclado1 = new javax.swing.JLabel();
        painel_mouse1 = new javax.swing.JPanel();
        btn_mouse1 = new javax.swing.JButton();
        txt_descricao_mouse1 = new javax.swing.JLabel();
        txt_preco_mouse1 = new javax.swing.JLabel();
        painel_som1 = new javax.swing.JPanel();
        btn_caixa_de_som1 = new javax.swing.JButton();
        txt_descricao_de_som1 = new javax.swing.JLabel();
        txt_preco_de_som1 = new javax.swing.JLabel();
        pianel_gabinete1 = new javax.swing.JPanel();
        btn_gabinete1 = new javax.swing.JButton();
        txt_descricao_gabinete1 = new javax.swing.JLabel();
        txt_preco_gabinete1 = new javax.swing.JLabel();
        pianel_mousepad1 = new javax.swing.JPanel();
        btn_mousepad1 = new javax.swing.JButton();
        txt_descricao_mousepad1 = new javax.swing.JLabel();
        txt_preco_mousepad1 = new javax.swing.JLabel();
        painel_placa_de_video1 = new javax.swing.JPanel();
        btn_placa_de_video1 = new javax.swing.JButton();
        txt_descricao_placa_de_video1 = new javax.swing.JLabel();
        txt_preco_placa_de_video1 = new javax.swing.JLabel();
        painel_monitor2 = new javax.swing.JPanel();
        btn_monitor2 = new javax.swing.JButton();
        txt_descricao_monitor2 = new javax.swing.JLabel();
        txt_preco_monitor2 = new javax.swing.JLabel();
        painel_mouse2 = new javax.swing.JPanel();
        btn_mouse2 = new javax.swing.JButton();
        txt_descricao_mouse2 = new javax.swing.JLabel();
        txt_preco_mouse2 = new javax.swing.JLabel();
        painel_cooler1 = new javax.swing.JPanel();
        btn_cooler1 = new javax.swing.JButton();
        txt_descricao_cooler1 = new javax.swing.JLabel();
        txt_preco_cooler1 = new javax.swing.JLabel();
        painel_headset1 = new javax.swing.JPanel();
        btn_headset1 = new javax.swing.JButton();
        txt_descricao_headset1 = new javax.swing.JLabel();
        txt_preco_headset1 = new javax.swing.JLabel();
        painel_webcam1 = new javax.swing.JPanel();
        btn_webcam1 = new javax.swing.JButton();
        txt_descricao_webcam1 = new javax.swing.JLabel();
        txt_preco_webcam1 = new javax.swing.JLabel();
        painel_mousepad2 = new javax.swing.JPanel();
        btn_mousepad2 = new javax.swing.JButton();
        txt_descricao_mousepad2 = new javax.swing.JLabel();
        txt_preco_mousepad2 = new javax.swing.JLabel();
        painel_headset2 = new javax.swing.JPanel();
        btn_headset2 = new javax.swing.JButton();
        txt_descricao_headset2 = new javax.swing.JLabel();
        txt_preco_headset2 = new javax.swing.JLabel();
        painel_gabinete2 = new javax.swing.JPanel();
        btn_gabinete2 = new javax.swing.JButton();
        txt_descricao_gabinete2 = new javax.swing.JLabel();
        txt_preco_gabinete2 = new javax.swing.JLabel();
        painel_webcam2 = new javax.swing.JPanel();
        btn_webcam2 = new javax.swing.JButton();
        txt_descricao_webcam2 = new javax.swing.JLabel();
        txt_preco_webcam2 = new javax.swing.JLabel();
        painel_roteador1 = new javax.swing.JPanel();
        btn_roteador1 = new javax.swing.JButton();
        txt_descricao_roteador1 = new javax.swing.JLabel();
        txt_preco_roteador1 = new javax.swing.JLabel();
        painel_teclado2 = new javax.swing.JPanel();
        btn_teclado2 = new javax.swing.JButton();
        txt_descricao_teclado2 = new javax.swing.JLabel();
        txt_preco_teclado2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(946, 1979));

        primeiro.setBackground(new java.awt.Color(157, 93, 166));
        primeiro.setPreferredSize(new java.awt.Dimension(926, 2834));

        jPanel5.setBackground(new java.awt.Color(55, 16, 117));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/x33.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 255, 200));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/33seta.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.loja.gif"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(47, 16, 115));

        btn_historico.setBackground(new java.awt.Color(156, 78, 166));
        btn_historico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_historico.setForeground(new java.awt.Color(255, 255, 255));
        btn_historico.setText("Historico de Compras");
        btn_historico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historicoActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(156, 78, 164));
        btn_login.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Seu usuário");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_login1.setBackground(new java.awt.Color(156, 78, 164));
        btn_login1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_login1.setForeground(new java.awt.Color(255, 255, 255));
        btn_login1.setText("Seu carrinho");
        btn_login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(btn_login1)
                .addGap(18, 18, 18)
                .addComponent(btn_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_login)
                .addGap(244, 244, 244))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painel_monitor1.setBackground(new java.awt.Color(49, 16, 117));
        painel_monitor1.setPreferredSize(new java.awt.Dimension(239, 299));

        btn_monitor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/muniisss.png"))); // NOI18N
        btn_monitor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monitor1ActionPerformed(evt);
            }
        });

        txt_descricao_monitor1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_monitor1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_monitor1.setText("<html>Monitor Gamer Gigabyte 27', FHD <br> HDMI,/Displaypor t, 144Hz 1ms");

        txt_preco_monitor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_monitor1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_monitor1.setText("R$ 2.399,90");

        javax.swing.GroupLayout painel_monitor1Layout = new javax.swing.GroupLayout(painel_monitor1);
        painel_monitor1.setLayout(painel_monitor1Layout);
        painel_monitor1Layout.setHorizontalGroup(
            painel_monitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_monitor1Layout.createSequentialGroup()
                .addGroup(painel_monitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_monitor1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_monitor1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txt_preco_monitor1))
                    .addGroup(painel_monitor1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        painel_monitor1Layout.setVerticalGroup(
            painel_monitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_monitor1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(txt_preco_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pianel_telcado_1.setBackground(new java.awt.Color(55, 16, 117));
        pianel_telcado_1.setPreferredSize(new java.awt.Dimension(239, 299));

        btn_teclado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/teclado.png"))); // NOI18N
        btn_teclado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_teclado1ActionPerformed(evt);
            }
        });

        txt_descricao_teclado1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_teclado1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_teclado1.setText("<html>Teclado Mecânico Gamer <br> T-Dagger Bora <br> RGB, Switch Outemu Blue <br> ABNT2 - T-TGK315-BLUE");

        txt_preco_teclado1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_teclado1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_teclado1.setText("R$ 219,90");

        javax.swing.GroupLayout pianel_telcado_1Layout = new javax.swing.GroupLayout(pianel_telcado_1);
        pianel_telcado_1.setLayout(pianel_telcado_1Layout);
        pianel_telcado_1Layout.setHorizontalGroup(
            pianel_telcado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pianel_telcado_1Layout.createSequentialGroup()
                .addGroup(pianel_telcado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pianel_telcado_1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pianel_telcado_1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txt_descricao_teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pianel_telcado_1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txt_preco_teclado1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pianel_telcado_1Layout.setVerticalGroup(
            pianel_telcado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pianel_telcado_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_preco_teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        painel_mouse1.setBackground(new java.awt.Color(55, 16, 117));

        btn_mouse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/ms.png"))); // NOI18N
        btn_mouse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mouse1ActionPerformed(evt);
            }
        });

        txt_descricao_mouse1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_mouse1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_mouse1.setText("<html>Mouse Gamer Dazz Kirata<br> Ascendent  RGB, 8 Botões <br>12400DPI");

        txt_preco_mouse1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_mouse1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_mouse1.setText("R$ 149,90");

        javax.swing.GroupLayout painel_mouse1Layout = new javax.swing.GroupLayout(painel_mouse1);
        painel_mouse1.setLayout(painel_mouse1Layout);
        painel_mouse1Layout.setHorizontalGroup(
            painel_mouse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_mouse1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txt_preco_mouse1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_mouse1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel_mouse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_mouse1Layout.createSequentialGroup()
                        .addComponent(btn_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_mouse1Layout.createSequentialGroup()
                        .addComponent(txt_descricao_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        painel_mouse1Layout.setVerticalGroup(
            painel_mouse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_mouse1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txt_preco_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_som1.setBackground(new java.awt.Color(55, 16, 117));
        painel_som1.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_caixa_de_som1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/som.png"))); // NOI18N
        btn_caixa_de_som1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caixa_de_som1ActionPerformed(evt);
            }
        });

        txt_descricao_de_som1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_de_som1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_de_som1.setText("<html>Caixa de Som Gamer Husky <br> Gaming Storm, Preto, 6W, USB <br> P2, Rainbow - CX-HST-RA");

        txt_preco_de_som1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_de_som1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_de_som1.setText("R$ 69,90");

        javax.swing.GroupLayout painel_som1Layout = new javax.swing.GroupLayout(painel_som1);
        painel_som1.setLayout(painel_som1Layout);
        painel_som1Layout.setHorizontalGroup(
            painel_som1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_som1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_caixa_de_som1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(painel_som1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_som1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(txt_descricao_de_som1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
            .addGroup(painel_som1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_som1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(txt_preco_de_som1)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        painel_som1Layout.setVerticalGroup(
            painel_som1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_som1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_caixa_de_som1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(painel_som1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_som1Layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(txt_descricao_de_som1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
            .addGroup(painel_som1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_som1Layout.createSequentialGroup()
                    .addContainerGap(262, Short.MAX_VALUE)
                    .addComponent(txt_preco_de_som1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pianel_gabinete1.setBackground(new java.awt.Color(55, 16, 117));
        pianel_gabinete1.setPreferredSize(new java.awt.Dimension(239, 299));

        btn_gabinete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/gabinete.png"))); // NOI18N
        btn_gabinete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gabinete1ActionPerformed(evt);
            }
        });

        txt_descricao_gabinete1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_gabinete1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_gabinete1.setText("<html>Gabinete Gamer Corsair <br> Carbide Series Spec Delta<br> RGB Mid-Tower 3 Fans <br>.Vidro Temperado <br> Preto CC-9011166-WW");

        txt_preco_gabinete1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_gabinete1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_gabinete1.setText("R$ 799,90");

        javax.swing.GroupLayout pianel_gabinete1Layout = new javax.swing.GroupLayout(pianel_gabinete1);
        pianel_gabinete1.setLayout(pianel_gabinete1Layout);
        pianel_gabinete1Layout.setHorizontalGroup(
            pianel_gabinete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pianel_gabinete1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(pianel_gabinete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pianel_gabinete1Layout.createSequentialGroup()
                        .addComponent(btn_gabinete1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pianel_gabinete1Layout.createSequentialGroup()
                        .addComponent(txt_descricao_gabinete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(pianel_gabinete1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txt_preco_gabinete1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pianel_gabinete1Layout.setVerticalGroup(
            pianel_gabinete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pianel_gabinete1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_gabinete1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_descricao_gabinete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txt_preco_gabinete1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pianel_mousepad1.setBackground(new java.awt.Color(55, 16, 117));
        pianel_mousepad1.setPreferredSize(new java.awt.Dimension(239, 301));

        btn_mousepad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/mousepad.png"))); // NOI18N
        btn_mousepad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mousepad1ActionPerformed(evt);
            }
        });

        txt_descricao_mousepad1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_mousepad1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_mousepad1.setText("<html> Mousepad Gamer <br> HyperX Fury S Speed <br> Extra Grande (900x420mm) <br> - HX-MPFS-S-XL");

        txt_preco_mousepad1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_mousepad1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_mousepad1.setText("R$ 189,99");

        javax.swing.GroupLayout pianel_mousepad1Layout = new javax.swing.GroupLayout(pianel_mousepad1);
        pianel_mousepad1.setLayout(pianel_mousepad1Layout);
        pianel_mousepad1Layout.setHorizontalGroup(
            pianel_mousepad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pianel_mousepad1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_descricao_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(pianel_mousepad1Layout.createSequentialGroup()
                .addGroup(pianel_mousepad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pianel_mousepad1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pianel_mousepad1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txt_preco_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pianel_mousepad1Layout.setVerticalGroup(
            pianel_mousepad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pianel_mousepad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_preco_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_placa_de_video1.setBackground(new java.awt.Color(55, 16, 117));
        painel_placa_de_video1.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_placa_de_video1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/placa.png"))); // NOI18N
        btn_placa_de_video1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_placa_de_video1ActionPerformed(evt);
            }
        });

        txt_descricao_placa_de_video1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_placa_de_video1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_placa_de_video1.setText("<html>Placa de Vídeo Gigabyte <br> NVIDIA GeForce RTX 2060 D6 6G <br>GDDR6 - GV-N2060D6-6GD");

        txt_preco_placa_de_video1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_placa_de_video1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_placa_de_video1.setText("R$ 3.999,90");

        javax.swing.GroupLayout painel_placa_de_video1Layout = new javax.swing.GroupLayout(painel_placa_de_video1);
        painel_placa_de_video1.setLayout(painel_placa_de_video1Layout);
        painel_placa_de_video1Layout.setHorizontalGroup(
            painel_placa_de_video1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_placa_de_video1Layout.createSequentialGroup()
                .addGroup(painel_placa_de_video1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_placa_de_video1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_placa_de_video1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_placa_de_video1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txt_preco_placa_de_video1))
                    .addGroup(painel_placa_de_video1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_placa_de_video1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        painel_placa_de_video1Layout.setVerticalGroup(
            painel_placa_de_video1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_placa_de_video1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_placa_de_video1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_descricao_placa_de_video1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_preco_placa_de_video1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_monitor2.setBackground(new java.awt.Color(55, 16, 117));
        painel_monitor2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_monitor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/monitor2.png"))); // NOI18N
        btn_monitor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monitor2ActionPerformed(evt);
            }
        });

        txt_descricao_monitor2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_monitor2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_monitor2.setText("<html>Monitor Gamer LG 34' IPS, Curvo<br> Ultra Wid 44 Hz, Full HD<br> 1ms, FreeSync, HDR");

        txt_preco_monitor2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_monitor2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_monitor2.setText("R$ 2.899,90");

        javax.swing.GroupLayout painel_monitor2Layout = new javax.swing.GroupLayout(painel_monitor2);
        painel_monitor2.setLayout(painel_monitor2Layout);
        painel_monitor2Layout.setHorizontalGroup(
            painel_monitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_monitor2Layout.createSequentialGroup()
                .addGroup(painel_monitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_monitor2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_monitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_descricao_monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painel_monitor2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txt_preco_monitor2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_monitor2Layout.setVerticalGroup(
            painel_monitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_monitor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(txt_preco_monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_mouse2.setBackground(new java.awt.Color(55, 16, 117));
        painel_mouse2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_mouse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/mouse2.png"))); // NOI18N
        btn_mouse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mouse2ActionPerformed(evt);
            }
        });

        txt_descricao_mouse2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_mouse2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_mouse2.setText("<html>Mouse Gamer Husky Gaming Frost <br> Branco  12000 DPI, 7 Botões, RGB <br>HGMH006");

        txt_preco_mouse2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_mouse2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_mouse2.setText("R$ 209,90");

        javax.swing.GroupLayout painel_mouse2Layout = new javax.swing.GroupLayout(painel_mouse2);
        painel_mouse2.setLayout(painel_mouse2Layout);
        painel_mouse2Layout.setHorizontalGroup(
            painel_mouse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_mouse2Layout.createSequentialGroup()
                .addGroup(painel_mouse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_mouse2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_mouse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_mouse2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_descricao_mouse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painel_mouse2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txt_preco_mouse2)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        painel_mouse2Layout.setVerticalGroup(
            painel_mouse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_mouse2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_mouse2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_mouse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_preco_mouse2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_cooler1.setBackground(new java.awt.Color(55, 16, 117));
        painel_cooler1.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_cooler1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/cooler.png"))); // NOI18N
        btn_cooler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cooler1ActionPerformed(evt);
            }
        });

        txt_descricao_cooler1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_cooler1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_cooler1.setText("<html>Cooler FAN XPG, 120mm, ARGB<br> Branco - VENTO120ARGB-BKCWW");

        txt_preco_cooler1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_cooler1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_cooler1.setText("R$ 49,90");

        javax.swing.GroupLayout painel_cooler1Layout = new javax.swing.GroupLayout(painel_cooler1);
        painel_cooler1.setLayout(painel_cooler1Layout);
        painel_cooler1Layout.setHorizontalGroup(
            painel_cooler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cooler1Layout.createSequentialGroup()
                .addGroup(painel_cooler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_cooler1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_cooler1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_cooler1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_cooler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_cooler1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_cooler1)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        painel_cooler1Layout.setVerticalGroup(
            painel_cooler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cooler1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cooler1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_cooler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_preco_cooler1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_headset1.setBackground(new java.awt.Color(55, 16, 117));
        painel_headset1.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_headset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/headset.png"))); // NOI18N
        btn_headset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_headset1ActionPerformed(evt);
            }
        });

        txt_descricao_headset1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_headset1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_headset1.setText("<html>Headset Sem Fio Gamer HyperX <br>Cloud II Som Surround 7.1, Drivers <br> 53mm, Preto e Vermelho");

        txt_preco_headset1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_headset1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_headset1.setText("R$ 799,90");

        javax.swing.GroupLayout painel_headset1Layout = new javax.swing.GroupLayout(painel_headset1);
        painel_headset1.setLayout(painel_headset1Layout);
        painel_headset1Layout.setHorizontalGroup(
            painel_headset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headset1Layout.createSequentialGroup()
                .addGroup(painel_headset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_headset1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_headset1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_headset1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_headset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_headset1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_headset1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_headset1Layout.setVerticalGroup(
            painel_headset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headset1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_headset1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_headset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_preco_headset1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_webcam1.setBackground(new java.awt.Color(55, 16, 117));
        painel_webcam1.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_webcam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/webcam1.png"))); // NOI18N
        btn_webcam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_webcam1ActionPerformed(evt);
            }
        });

        txt_descricao_webcam1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_webcam1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_webcam1.setText("<html>Webcam Full HD Logitech C922 Pro <br>Stream com Microfone Embutido <br> USB, 1080p e Tripé Incluso <br>Compatível Logitech Capture");

        txt_preco_webcam1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_webcam1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_webcam1.setText("R$ 489,90");

        javax.swing.GroupLayout painel_webcam1Layout = new javax.swing.GroupLayout(painel_webcam1);
        painel_webcam1.setLayout(painel_webcam1Layout);
        painel_webcam1Layout.setHorizontalGroup(
            painel_webcam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_webcam1Layout.createSequentialGroup()
                .addGroup(painel_webcam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_webcam1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_webcam1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_webcam1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_webcam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_webcam1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txt_preco_webcam1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_webcam1Layout.setVerticalGroup(
            painel_webcam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_webcam1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_webcam1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_webcam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_preco_webcam1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        painel_mousepad2.setBackground(new java.awt.Color(55, 16, 117));
        painel_mousepad2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_mousepad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/mousepad2.png"))); // NOI18N
        btn_mousepad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mousepad2ActionPerformed(evt);
            }
        });

        txt_descricao_mousepad2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_mousepad2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_mousepad2.setText("<html>Mousepad Gamer HyperX <br>Fury S Speed Grande <br> (450x400mm) - HX-MPFS-S-L");

        txt_preco_mousepad2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_mousepad2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_mousepad2.setText("R$ 84,90");

        javax.swing.GroupLayout painel_mousepad2Layout = new javax.swing.GroupLayout(painel_mousepad2);
        painel_mousepad2.setLayout(painel_mousepad2Layout);
        painel_mousepad2Layout.setHorizontalGroup(
            painel_mousepad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_mousepad2Layout.createSequentialGroup()
                .addGroup(painel_mousepad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_mousepad2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_mousepad2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_mousepad2))
                    .addGroup(painel_mousepad2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txt_descricao_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_mousepad2Layout.setVerticalGroup(
            painel_mousepad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_mousepad2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txt_preco_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_headset2.setBackground(new java.awt.Color(55, 16, 117));
        painel_headset2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_headset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/headset2.png"))); // NOI18N
        btn_headset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_headset2ActionPerformed(evt);
            }
        });

        txt_descricao_headset2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_headset2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_headset2.setText("<html>Headset Sem Fio Gamer Corsair <br> Virtuoso Premium Carbono, RGB <br> Som  Surround 7.1, Drivers 50mm <br>Múltiplas Plataformas");

        txt_preco_headset2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_headset2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_headset2.setText("R$ 799,90");

        javax.swing.GroupLayout painel_headset2Layout = new javax.swing.GroupLayout(painel_headset2);
        painel_headset2.setLayout(painel_headset2Layout);
        painel_headset2Layout.setHorizontalGroup(
            painel_headset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headset2Layout.createSequentialGroup()
                .addGroup(painel_headset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_headset2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_headset2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_headset2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_headset2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_headset2Layout.setVerticalGroup(
            painel_headset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headset2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(txt_preco_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_gabinete2.setBackground(new java.awt.Color(55, 16, 117));
        painel_gabinete2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_gabinete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/gabinete2.png"))); // NOI18N
        btn_gabinete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gabinete2ActionPerformed(evt);
            }
        });

        txt_descricao_gabinete2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_gabinete2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_gabinete2.setText("<html>Gabinete Gamer Gigabyte C200G<br> Mid Tower, RGB, Lateral e Fronta <br> em Vidro - 28300-GC20G-1CKR");

        txt_preco_gabinete2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_gabinete2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_gabinete2.setText("R$ 699,90");

        javax.swing.GroupLayout painel_gabinete2Layout = new javax.swing.GroupLayout(painel_gabinete2);
        painel_gabinete2.setLayout(painel_gabinete2Layout);
        painel_gabinete2Layout.setHorizontalGroup(
            painel_gabinete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_gabinete2Layout.createSequentialGroup()
                .addGroup(painel_gabinete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_gabinete2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_gabinete2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_gabinete2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_gabinete2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_gabinete2Layout.setVerticalGroup(
            painel_gabinete2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_gabinete2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txt_preco_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_webcam2.setBackground(new java.awt.Color(55, 16, 117));
        painel_webcam2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_webcam2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/webcam2.png"))); // NOI18N
        btn_webcam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_webcam2ActionPerformed(evt);
            }
        });

        txt_descricao_webcam2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_webcam2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_webcam2.setText("<html>Webcam Kross, Full HD 1080P<br> Foco Manual, Tripé Ajustável <br> KE-WBM1080P");

        txt_preco_webcam2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_webcam2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_webcam2.setText("R$ 189,90");

        javax.swing.GroupLayout painel_webcam2Layout = new javax.swing.GroupLayout(painel_webcam2);
        painel_webcam2.setLayout(painel_webcam2Layout);
        painel_webcam2Layout.setHorizontalGroup(
            painel_webcam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_webcam2Layout.createSequentialGroup()
                .addGroup(painel_webcam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_webcam2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_webcam2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_webcam2))
                    .addGroup(painel_webcam2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_descricao_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_webcam2Layout.setVerticalGroup(
            painel_webcam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_webcam2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txt_preco_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_roteador1.setBackground(new java.awt.Color(55, 16, 117));
        painel_roteador1.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_roteador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/roteador1.png"))); // NOI18N
        btn_roteador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roteador1ActionPerformed(evt);
            }
        });

        txt_descricao_roteador1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_roteador1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_roteador1.setText("<html>Roteador TP-Link Archer C6 V3 <br>, AC1200, MU-MIMO, Wireless <br> Dual Band, 4x Antenas, Portas 4x<br> Gigabit (1x WAN, 4x LAN) ");

        txt_preco_roteador1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_roteador1.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_roteador1.setText("R$ 265,90");

        javax.swing.GroupLayout painel_roteador1Layout = new javax.swing.GroupLayout(painel_roteador1);
        painel_roteador1.setLayout(painel_roteador1Layout);
        painel_roteador1Layout.setHorizontalGroup(
            painel_roteador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_roteador1Layout.createSequentialGroup()
                .addGroup(painel_roteador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_roteador1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_roteador1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_roteador1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_roteador1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_roteador1Layout.setVerticalGroup(
            painel_roteador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_roteador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(txt_preco_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painel_teclado2.setBackground(new java.awt.Color(55, 16, 117));
        painel_teclado2.setPreferredSize(new java.awt.Dimension(239, 310));

        btn_teclado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_imagens_produtos/teclado2..png"))); // NOI18N
        btn_teclado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_teclado2ActionPerformed(evt);
            }
        });

        txt_descricao_teclado2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_descricao_teclado2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descricao_teclado2.setText("<html>Teclado Mecânico Gamer HyperX<br> Alloy Origins RGB, Switch HyperX<br> Red, ABNT2  - HX-KB6RDX-BR");

        txt_preco_teclado2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_preco_teclado2.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco_teclado2.setText("R$ 579,90");

        javax.swing.GroupLayout painel_teclado2Layout = new javax.swing.GroupLayout(painel_teclado2);
        painel_teclado2.setLayout(painel_teclado2Layout);
        painel_teclado2Layout.setHorizontalGroup(
            painel_teclado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_teclado2Layout.createSequentialGroup()
                .addGroup(painel_teclado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_teclado2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_teclado2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_descricao_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_teclado2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_preco_teclado2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        painel_teclado2Layout.setVerticalGroup(
            painel_teclado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_teclado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descricao_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txt_preco_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout primeiroLayout = new javax.swing.GroupLayout(primeiro);
        primeiro.setLayout(primeiroLayout);
        primeiroLayout.setHorizontalGroup(
            primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primeiroLayout.createSequentialGroup()
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(primeiroLayout.createSequentialGroup()
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(primeiroLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painel_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel_cooler1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel_som1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel_placa_de_video1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(primeiroLayout.createSequentialGroup()
                                    .addComponent(pianel_gabinete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pianel_mousepad1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(primeiroLayout.createSequentialGroup()
                                    .addComponent(pianel_telcado_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(painel_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(primeiroLayout.createSequentialGroup()
                                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(painel_headset1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painel_monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painel_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painel_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(painel_mouse2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painel_webcam1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painel_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painel_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(primeiroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        primeiroLayout.setVerticalGroup(
            primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primeiroLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pianel_telcado_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_monitor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_mouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_som1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pianel_mousepad1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addComponent(pianel_gabinete1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_monitor2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(painel_placa_de_video1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(painel_mouse2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painel_cooler1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(painel_headset1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(painel_webcam1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painel_mousepad2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_headset2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_gabinete2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(primeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painel_webcam2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_roteador1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_teclado2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(primeiro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 2550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();
        UI_login login = new UI_login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btn_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historicoActionPerformed
        UI_historico historico = new UI_historico();
        historico.setVisible(true);
    }//GEN-LAST:event_btn_historicoActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        UI_seu_usuario seu = new UI_seu_usuario();
        seu.setVisible(true);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
        UI_carrinho carrinho = new UI_carrinho();
        carrinho.setVisible(true);
    }//GEN-LAST:event_btn_login1ActionPerformed

    private void btn_monitor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monitor1ActionPerformed
        UI_monitor1 monitor = new UI_monitor1();
        monitor.setVisible(true);
    }//GEN-LAST:event_btn_monitor1ActionPerformed

    private void btn_teclado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teclado1ActionPerformed
        UI_tecladoo1 teclado = new UI_tecladoo1();
        teclado.setVisible(true);
    }//GEN-LAST:event_btn_teclado1ActionPerformed

    private void btn_mouse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mouse1ActionPerformed
        UI_mouse1 mouse = new UI_mouse1();
        mouse.setVisible(true);
    }//GEN-LAST:event_btn_mouse1ActionPerformed

    private void btn_caixa_de_som1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caixa_de_som1ActionPerformed
        UI_caixa_de_som1 som = new UI_caixa_de_som1();
        som.setVisible(true);
    }//GEN-LAST:event_btn_caixa_de_som1ActionPerformed

    private void btn_gabinete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gabinete1ActionPerformed
        UI_monitor1 gabinete = new UI_monitor1();
        gabinete.setVisible(true);
    }//GEN-LAST:event_btn_gabinete1ActionPerformed

    private void btn_mousepad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mousepad1ActionPerformed
        UI_mousepad1 mousepad = new UI_mousepad1();
        mousepad.setVisible(true);
    }//GEN-LAST:event_btn_mousepad1ActionPerformed

    private void btn_placa_de_video1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_placa_de_video1ActionPerformed
        UI_placa_de_video1  placa = new UI_placa_de_video1();
        placa.setVisible(true);
    }//GEN-LAST:event_btn_placa_de_video1ActionPerformed

    private void btn_monitor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monitor2ActionPerformed
       UI_monitor2 monitor = new UI_monitor2();
       monitor.setVisible(true);
    }//GEN-LAST:event_btn_monitor2ActionPerformed

    private void btn_mouse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mouse2ActionPerformed
        UI_mouse2 mouse = new UI_mouse2();
        mouse.setVisible(true);
    }//GEN-LAST:event_btn_mouse2ActionPerformed

    private void btn_cooler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cooler1ActionPerformed
      UI_cooler1 cooler = new UI_cooler1();
      cooler.setVisible(true);
    }//GEN-LAST:event_btn_cooler1ActionPerformed

    private void btn_headset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_headset1ActionPerformed
       UI_headset1 fone = new UI_headset1();
       fone.setVisible(true);
    }//GEN-LAST:event_btn_headset1ActionPerformed

    private void btn_webcam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_webcam1ActionPerformed
        UI_webcam1 web = new UI_webcam1();
        web.setVisible(true);
    }//GEN-LAST:event_btn_webcam1ActionPerformed

    private void btn_mousepad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mousepad2ActionPerformed
        UI_mousepad22 mousepad = new UI_mousepad22();
        mousepad.setVisible(true);
    }//GEN-LAST:event_btn_mousepad2ActionPerformed

    private void btn_headset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_headset2ActionPerformed
        UI_headset2 headset = new UI_headset2();
        headset.setVisible(true);
    }//GEN-LAST:event_btn_headset2ActionPerformed

    private void btn_gabinete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gabinete2ActionPerformed
        UI_gabinete2 gabinete = new UI_gabinete2();
        gabinete.setVisible(true);
    }//GEN-LAST:event_btn_gabinete2ActionPerformed

    private void btn_webcam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_webcam2ActionPerformed
        UI_webcam22 webcam = new UI_webcam22();
        webcam.setVisible(true);
    }//GEN-LAST:event_btn_webcam2ActionPerformed

    private void btn_roteador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roteador1ActionPerformed
        UI_roteador1 rote = new UI_roteador1();
        rote.setVisible(true);
    }//GEN-LAST:event_btn_roteador1ActionPerformed

    private void btn_teclado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teclado2ActionPerformed
        UI_tecladoo22 teclado = new UI_tecladoo22();
        teclado.setVisible(true);
    }//GEN-LAST:event_btn_teclado2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UI_produtos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caixa_de_som1;
    private javax.swing.JButton btn_cooler1;
    private javax.swing.JButton btn_gabinete1;
    private javax.swing.JButton btn_gabinete2;
    private javax.swing.JButton btn_headset1;
    private javax.swing.JButton btn_headset2;
    private javax.swing.JButton btn_historico;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_login1;
    private javax.swing.JButton btn_monitor1;
    private javax.swing.JButton btn_monitor2;
    private javax.swing.JButton btn_mouse1;
    private javax.swing.JButton btn_mouse2;
    private javax.swing.JButton btn_mousepad1;
    private javax.swing.JButton btn_mousepad2;
    private javax.swing.JButton btn_placa_de_video1;
    private javax.swing.JButton btn_roteador1;
    private javax.swing.JButton btn_teclado1;
    private javax.swing.JButton btn_teclado2;
    private javax.swing.JButton btn_webcam1;
    private javax.swing.JButton btn_webcam2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painel_cooler1;
    private javax.swing.JPanel painel_gabinete2;
    private javax.swing.JPanel painel_headset1;
    private javax.swing.JPanel painel_headset2;
    private javax.swing.JPanel painel_monitor1;
    private javax.swing.JPanel painel_monitor2;
    private javax.swing.JPanel painel_mouse1;
    private javax.swing.JPanel painel_mouse2;
    private javax.swing.JPanel painel_mousepad2;
    private javax.swing.JPanel painel_placa_de_video1;
    private javax.swing.JPanel painel_roteador1;
    private javax.swing.JPanel painel_som1;
    private javax.swing.JPanel painel_teclado2;
    private javax.swing.JPanel painel_webcam1;
    private javax.swing.JPanel painel_webcam2;
    private javax.swing.JPanel pianel_gabinete1;
    private javax.swing.JPanel pianel_mousepad1;
    private javax.swing.JPanel pianel_telcado_1;
    private javax.swing.JPanel primeiro;
    private javax.swing.JLabel txt_descricao_cooler1;
    private javax.swing.JLabel txt_descricao_de_som1;
    private javax.swing.JLabel txt_descricao_gabinete1;
    private javax.swing.JLabel txt_descricao_gabinete2;
    private javax.swing.JLabel txt_descricao_headset1;
    private javax.swing.JLabel txt_descricao_headset2;
    private javax.swing.JLabel txt_descricao_monitor1;
    private javax.swing.JLabel txt_descricao_monitor2;
    private javax.swing.JLabel txt_descricao_mouse1;
    private javax.swing.JLabel txt_descricao_mouse2;
    private javax.swing.JLabel txt_descricao_mousepad1;
    private javax.swing.JLabel txt_descricao_mousepad2;
    private javax.swing.JLabel txt_descricao_placa_de_video1;
    private javax.swing.JLabel txt_descricao_roteador1;
    private javax.swing.JLabel txt_descricao_teclado1;
    private javax.swing.JLabel txt_descricao_teclado2;
    private javax.swing.JLabel txt_descricao_webcam1;
    private javax.swing.JLabel txt_descricao_webcam2;
    private javax.swing.JLabel txt_preco_cooler1;
    private javax.swing.JLabel txt_preco_de_som1;
    private javax.swing.JLabel txt_preco_gabinete1;
    private javax.swing.JLabel txt_preco_gabinete2;
    private javax.swing.JLabel txt_preco_headset1;
    private javax.swing.JLabel txt_preco_headset2;
    private javax.swing.JLabel txt_preco_monitor1;
    private javax.swing.JLabel txt_preco_monitor2;
    private javax.swing.JLabel txt_preco_mouse1;
    private javax.swing.JLabel txt_preco_mouse2;
    private javax.swing.JLabel txt_preco_mousepad1;
    private javax.swing.JLabel txt_preco_mousepad2;
    private javax.swing.JLabel txt_preco_placa_de_video1;
    private javax.swing.JLabel txt_preco_roteador1;
    private javax.swing.JLabel txt_preco_teclado1;
    private javax.swing.JLabel txt_preco_teclado2;
    private javax.swing.JLabel txt_preco_webcam1;
    private javax.swing.JLabel txt_preco_webcam2;
    // End of variables declaration//GEN-END:variables
}
